### ISSUE TITLE
Create a FloatingWindow class

### ISSUE THREAD

**Issue by ghost** [dr-off/ao3-enhancement-suite#23]
A generic window class that encompasses all of the functionality of the hardcoded window the floating comment box uses.

These windows will also have minimize, maximize and close buttons with optional event handlers for each one (or at least close).

Maybe this is overengineering, since idk if anything else in this project will ever use windows like this, but I still think it'd be cleaner to make it more generic rather than hacking more shit into the comment box file.

**Comment by dr-off** [comment]
Actually, this would probably make more sense to use instead of the Modal class in various, if not all, cases.

**Comment by dr-off** [comment]
Implemented in 88dabdf.
